// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRxvwyNinWR1T_5bkg_as6vvC0SPkGtM',
    appId: '1:395304097708:web:8ee0b4c1bd9f7739924c09',
    messagingSenderId: '395304097708',
    projectId: 'mosab-abumoammar-f33e0',
    authDomain: 'mosab-abumoammar-f33e0.firebaseapp.com',
    storageBucket: 'mosab-abumoammar-f33e0.firebasestorage.app',
    measurementId: 'G-9RPZZ7TV00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqpxK3n5RMYZlFutEnZQd6xOAA9KtNVI',
    appId: '1:395304097708:android:f3d1b5b291cb1fba924c09',
    messagingSenderId: '395304097708',
    projectId: 'mosab-abumoammar-f33e0',
    storageBucket: 'mosab-abumoammar-f33e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tSazL2bozmYKZoMW61bihSnb8-v-CS0',
    appId: '1:395304097708:ios:da9ece2d8ac2d35d924c09',
    messagingSenderId: '395304097708',
    projectId: 'mosab-abumoammar-f33e0',
    storageBucket: 'mosab-abumoammar-f33e0.firebasestorage.app',
    iosBundleId: 'com.mosababumoammar.mosabAbumoammar',
  );
}
